//! InvitationRepo — pending org/project membership invitations.
//!
//! `invitations.token_hash` only stores SHA-256(token). Plain invitation tokens
//! are generated by the HTTP layer and returned once on create.

use crate::error::{DbError, DbResult};
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use gate_core::id::UserId;
use parking_lot::RwLock;
use sqlx::{PgPool, Row};
use std::collections::HashMap;
use uuid::Uuid;

#[derive(Debug, Clone)]
pub struct InvitationRecord {
    pub id: Uuid,
    pub scope_kind: String,
    pub scope_id: Uuid,
    pub email: String,
    pub role: String,
    pub token_hash: String,
    pub invited_by: UserId,
    pub expires_at: DateTime<Utc>,
    pub accepted_at: Option<DateTime<Utc>>,
    pub accepted_by: Option<UserId>,
    pub revoked_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

impl InvitationRecord {
    pub fn is_pending_at(&self, now: DateTime<Utc>) -> bool {
        self.accepted_at.is_none() && self.revoked_at.is_none() && self.expires_at > now
    }

    pub fn status_at(&self, now: DateTime<Utc>) -> &'static str {
        if self.revoked_at.is_some() {
            "revoked"
        } else if self.accepted_at.is_some() {
            "accepted"
        } else if self.expires_at <= now {
            "expired"
        } else {
            "pending"
        }
    }
}

#[derive(Debug, Clone)]
pub struct InvitationCreate {
    pub id: Uuid,
    pub scope_kind: String,
    pub scope_id: Uuid,
    pub email: String,
    pub role: String,
    pub token_hash: String,
    pub invited_by: UserId,
    pub expires_at: DateTime<Utc>,
}

#[async_trait]
pub trait InvitationRepo: Send + Sync + 'static {
    async fn create(&self, rec: InvitationCreate) -> DbResult<InvitationRecord>;
    async fn list_scope(
        &self,
        scope_kind: &str,
        scope_id: Uuid,
        include_inactive: bool,
    ) -> DbResult<Vec<InvitationRecord>>;
    async fn find_by_id(&self, id: Uuid) -> DbResult<InvitationRecord>;
    async fn find_by_token_hash(&self, token_hash: &str) -> DbResult<InvitationRecord>;
    async fn accept(&self, token_hash: &str, accepted_by: UserId) -> DbResult<InvitationRecord>;
    async fn revoke(&self, id: Uuid) -> DbResult<InvitationRecord>;
}

pub struct PgInvitationRepo {
    pool: PgPool,
}

impl PgInvitationRepo {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

const INVITATION_COLUMNS: &str = "id, scope_kind, scope_id, email::text AS email, role, token_hash, \
    invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at";

fn row_to_invitation(row: &sqlx::postgres::PgRow) -> DbResult<InvitationRecord> {
    let invited_by: Uuid = row.try_get("invited_by")?;
    let accepted_by: Option<Uuid> = row.try_get("accepted_by")?;
    Ok(InvitationRecord {
        id: row.try_get("id")?,
        scope_kind: row.try_get("scope_kind")?,
        scope_id: row.try_get("scope_id")?,
        email: row.try_get("email")?,
        role: row.try_get("role")?,
        token_hash: row.try_get("token_hash")?,
        invited_by: UserId::from(invited_by),
        expires_at: row.try_get("expires_at")?,
        accepted_at: row.try_get("accepted_at")?,
        accepted_by: accepted_by.map(UserId::from),
        revoked_at: row.try_get("revoked_at")?,
        created_at: row.try_get("created_at")?,
    })
}

#[async_trait]
impl InvitationRepo for PgInvitationRepo {
    async fn create(&self, rec: InvitationCreate) -> DbResult<InvitationRecord> {
        let row = sqlx::query(&format!(
            "INSERT INTO invitations \
             (id, scope_kind, scope_id, email, role, token_hash, invited_by, expires_at) \
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8) \
             RETURNING {INVITATION_COLUMNS}"
        ))
        .bind(rec.id)
        .bind(&rec.scope_kind)
        .bind(rec.scope_id)
        .bind(&rec.email)
        .bind(&rec.role)
        .bind(&rec.token_hash)
        .bind(rec.invited_by.as_uuid())
        .bind(rec.expires_at)
        .fetch_one(&self.pool)
        .await?;
        row_to_invitation(&row)
    }

    async fn list_scope(
        &self,
        scope_kind: &str,
        scope_id: Uuid,
        include_inactive: bool,
    ) -> DbResult<Vec<InvitationRecord>> {
        let sql = if include_inactive {
            format!(
                "SELECT {INVITATION_COLUMNS} FROM invitations \
                 WHERE scope_kind = $1 AND scope_id = $2 \
                 ORDER BY created_at DESC"
            )
        } else {
            format!(
                "SELECT {INVITATION_COLUMNS} FROM invitations \
                 WHERE scope_kind = $1 AND scope_id = $2 \
                   AND accepted_at IS NULL AND revoked_at IS NULL \
                   AND expires_at > NOW() \
                 ORDER BY created_at DESC"
            )
        };
        let rows = sqlx::query(&sql)
            .bind(scope_kind)
            .bind(scope_id)
            .fetch_all(&self.pool)
            .await?;
        rows.iter().map(row_to_invitation).collect()
    }

    async fn find_by_id(&self, id: Uuid) -> DbResult<InvitationRecord> {
        let row = sqlx::query(&format!(
            "SELECT {INVITATION_COLUMNS} FROM invitations WHERE id = $1"
        ))
        .bind(id)
        .fetch_one(&self.pool)
        .await?;
        row_to_invitation(&row)
    }

    async fn find_by_token_hash(&self, token_hash: &str) -> DbResult<InvitationRecord> {
        let row = sqlx::query(&format!(
            "SELECT {INVITATION_COLUMNS} FROM invitations WHERE token_hash = $1"
        ))
        .bind(token_hash)
        .fetch_one(&self.pool)
        .await?;
        row_to_invitation(&row)
    }

    async fn accept(&self, token_hash: &str, accepted_by: UserId) -> DbResult<InvitationRecord> {
        let row = sqlx::query(&format!(
            "UPDATE invitations \
             SET accepted_at = NOW(), accepted_by = $2 \
             WHERE token_hash = $1 \
               AND accepted_at IS NULL \
               AND revoked_at IS NULL \
               AND expires_at > NOW() \
             RETURNING {INVITATION_COLUMNS}"
        ))
        .bind(token_hash)
        .bind(accepted_by.as_uuid())
        .fetch_optional(&self.pool)
        .await?;
        let Some(row) = row else {
            return Err(DbError::Conflict("invitation is not pending".into()));
        };
        row_to_invitation(&row)
    }

    async fn revoke(&self, id: Uuid) -> DbResult<InvitationRecord> {
        let row = sqlx::query(&format!(
            "UPDATE invitations \
             SET revoked_at = NOW() \
             WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL \
             RETURNING {INVITATION_COLUMNS}"
        ))
        .bind(id)
        .fetch_optional(&self.pool)
        .await?;
        let Some(row) = row else {
            return Err(DbError::Conflict("invitation is not pending".into()));
        };
        row_to_invitation(&row)
    }
}

#[derive(Default)]
pub struct InMemoryInvitationRepo {
    inner: RwLock<InvitationInner>,
}

#[derive(Default)]
struct InvitationInner {
    by_id: HashMap<Uuid, InvitationRecord>,
    by_token_hash: HashMap<String, Uuid>,
}

impl InMemoryInvitationRepo {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn seed(&self, rec: InvitationRecord) {
        let mut g = self.inner.write();
        g.by_token_hash.insert(rec.token_hash.clone(), rec.id);
        g.by_id.insert(rec.id, rec);
    }
}

#[async_trait]
impl InvitationRepo for InMemoryInvitationRepo {
    async fn create(&self, rec: InvitationCreate) -> DbResult<InvitationRecord> {
        let mut g = self.inner.write();
        if g.by_id.contains_key(&rec.id) || g.by_token_hash.contains_key(&rec.token_hash) {
            return Err(DbError::Conflict("invitation already exists".into()));
        }
        let now = Utc::now();
        let record = InvitationRecord {
            id: rec.id,
            scope_kind: rec.scope_kind,
            scope_id: rec.scope_id,
            email: rec.email,
            role: rec.role,
            token_hash: rec.token_hash,
            invited_by: rec.invited_by,
            expires_at: rec.expires_at,
            accepted_at: None,
            accepted_by: None,
            revoked_at: None,
            created_at: now,
        };
        g.by_token_hash.insert(record.token_hash.clone(), record.id);
        g.by_id.insert(record.id, record.clone());
        Ok(record)
    }

    async fn list_scope(
        &self,
        scope_kind: &str,
        scope_id: Uuid,
        include_inactive: bool,
    ) -> DbResult<Vec<InvitationRecord>> {
        let now = Utc::now();
        let mut records: Vec<_> = self
            .inner
            .read()
            .by_id
            .values()
            .filter(|rec| rec.scope_kind == scope_kind && rec.scope_id == scope_id)
            .filter(|rec| include_inactive || rec.is_pending_at(now))
            .cloned()
            .collect();
        records.sort_by_key(|rec| std::cmp::Reverse(rec.created_at));
        Ok(records)
    }

    async fn find_by_id(&self, id: Uuid) -> DbResult<InvitationRecord> {
        self.inner
            .read()
            .by_id
            .get(&id)
            .cloned()
            .ok_or(DbError::NotFound)
    }

    async fn find_by_token_hash(&self, token_hash: &str) -> DbResult<InvitationRecord> {
        let g = self.inner.read();
        g.by_token_hash
            .get(token_hash)
            .and_then(|id| g.by_id.get(id))
            .cloned()
            .ok_or(DbError::NotFound)
    }

    async fn accept(&self, token_hash: &str, accepted_by: UserId) -> DbResult<InvitationRecord> {
        let mut g = self.inner.write();
        let id = *g.by_token_hash.get(token_hash).ok_or(DbError::NotFound)?;
        let rec = g.by_id.get_mut(&id).ok_or(DbError::NotFound)?;
        if !rec.is_pending_at(Utc::now()) {
            return Err(DbError::Conflict("invitation is not pending".into()));
        }
        rec.accepted_at = Some(Utc::now());
        rec.accepted_by = Some(accepted_by);
        Ok(rec.clone())
    }

    async fn revoke(&self, id: Uuid) -> DbResult<InvitationRecord> {
        let mut g = self.inner.write();
        let rec = g.by_id.get_mut(&id).ok_or(DbError::NotFound)?;
        if !rec.is_pending_at(Utc::now()) {
            return Err(DbError::Conflict("invitation is not pending".into()));
        }
        rec.revoked_at = Some(Utc::now());
        Ok(rec.clone())
    }
}
