apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kooix-gate.fullname" . }}
type: Opaque
stringData:
  KOOIX_MASTER_KEY: {{ required "secretEnv.KOOIX_MASTER_KEY is required" .Values.secretEnv.KOOIX_MASTER_KEY | quote }}
  KOOIX_JWT_SECRET: {{ required "secretEnv.KOOIX_JWT_SECRET is required" .Values.secretEnv.KOOIX_JWT_SECRET | quote }}
  {{ with .Values.secretEnv.KOOIX_JWT_PREVIOUS_SECRETS }}
  KOOIX_JWT_PREVIOUS_SECRETS: {{ . | quote }}
  {{ end }}
